routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
use App\Notifications\ExpirationWarning;

    // Home Page route

    // Route::get('/', function () {





    //         return route('page.home');


    // })->name('home');









    /**
     *
     *  AUTH MIDDLEWARE
     *
     *
     */


    Route::group(['middleware' => 'auth'], function () {

        // All my routes that needs a logged in user
        Route::get('/checkout', 'NewListingsController@showPaymentForm')->name('paymentform');

        // Dashboard Routes
        Route::get('dashboard', 'DashboardController@index')->name('dashboard');

        // Shows order history
        Route::get('dashboard/billing/', 'DashboardController@billing')->name('dashboard.billing');

        // Displays the listings management - Note: This will be changed to new routes for each listing type.
        Route::get('dashboard/listings', 'DashboardController@listings')->name('dashboard.listings');


                /**
                 *  Credit Card Stripe Routes
                 */
        
                // AJAX route for CCs
                Route::get('dashboard/ccAjax', 'DashboardController@ccAjax')->name('dashboard.ccAjax');
                
                // Route to handle setting stripe default
                Route::post('dashboard/newdefault', 'DashboardController@setNewDefault')->name('dashboard.newDefault');
                
                // Add a credit card
                Route::post('dashboard/addcreditcard', 'DashboardController@addCreditCard')->name('dashboard.addCreditCard');

                // Delete Credit Cards
                Route::post('dashboard/deletecard', 'DashboardController@deleteCard')->name('dashboard.deleteCard');


        // Show invoices
        Route::get('dashboard/invoices', 'DashboardController@invoices')->name('dashboard.invoices');

        // Route to download an invoice by ID
        Route::get('/dashboard/invoices/download/{id}', 'InvoiceController@download')->name('dashboard.billing.download');

                /**
                 *
                 * User Profile Routes
                 *
                 */

                //Show user profile
                Route::get('dashboard/profile', 'DashboardController@profile')->name('dashboard.profile');
                
                // Update user data
                Route::post('dashboard/profile/update', 'DashboardController@updateUser')->name('dashboard.updateuser');

                // Remove the avatar file route
                Route::get('dashboard/profile/removeavatar', 'DashboardController@removeAvatar')->name('dashboard.removeavatar');


        // Show notifications
        Route::get('dashboard/notifications', 'DashboardController@messages')->name('dashboard.messages');

        // Messages controller
        Route::resource('message', 'MessageController');

        Route::get('dashboard/membership', 'DashboardController@membership')->name('dashboard.membership');
        Route::post('dashboard/membership/cancel/process', 'DashboardController@cancelSubscription')->name('dashboard.membership.cancel');

            /**
             *  Active Search Routes - Note: This is still in alpha stage. Not operational at this time.
             */
            
            // Route::get('dashboard/activesearch','DashboardController@activesearch')->name('dashboard.activesearch');
            // Route::post('dashboard/activesearch/create','DashboardController@activeSearchCreate')->name('dashboard.activesearchcreate');

        // Orders Resource
        Route::resource('orders', 'OrderController');
        // Route::resource('apus', 'MessageController');

        // Aircraft Resource 
        Route::resource('aircraft', 'AircraftController');

        //Read Message Post - Note: This is a legacy AJAX handler
        Route::post('dashboard/message/read', 'MessageController@readMessage');

        // Invoices Resource
        Route::resource('invoices', 'InvoiceController@index');

        // Favorite Resource <3
        Route::resource('favorite', 'FavoritesController@index');

       // Page Resource
        Route::resource('page', 'PageController');

        // Home page
        Route::get('/', 'PageController@home')->name('home');



        // New Listings Routes
        Route::get('/new', 'NewListingsController@index')->name('newlisting');
        Route::get('/new/apu', 'NewListingsController@apu')->name('newapulisting');
    });




    /**
     *
     *      STRIPE
     *
     *      Note: This runs through a second middleware called a stripe_check, which ensures the user has a default payment method set up before *      completing
     *
     */



    // Show checkout page
    Route::get('/checkout', 'NewListingsController@showPaymentForm')->name('paymentform')->middleware('auth', 'stripe_check');

    // Process Payment
    Route::post('/checkout/process', 'NewListingsController@processPayment')->name('processpayment')->middleware('auth', 'stripe_check');

    // Show Upgrade Page
    Route::get('dashboard/membership/upgrade', 'DashboardController@showUpgrade')->name('dashboard.membership.showupgrade')->middleware('auth', 'stripe_check');

    // Process Membership Upgrade
    Route::post('dashboard/membership/upgrade/process', 'DashboardController@processUpgrade')->name('dashboard.membership.processupgrade')->middleware('auth', 'stripe_check');




    // STRIPE WEBHOOK LISTENER - Note: This receives all requests from Stripe
    Route::post('stripe/webhook', 'StripeController@handleWebHook');



    /**
     *    /END STRIPE
     */




    // Search Results
    Route::get('search', 'SearchController@search')->name('search');

    // Log out
    Route::get('/logout', function () {

        Auth::logout();
        return redirect('/login')->with('success', 'successfully logged out');
    })->name('logout');


    // APU Resource Route - Note: This needs to be changed to partial routes, for auth purposes.
    Route::resource('apus', 'ApuController');

    // Engine Resource Route - Note: Ditto above.
    Route::resource('engines', 'EngineController');

    // Legacy Market routes that I may still use
    Route::get('market/ajax', 'MarketPostController@marketAjax');

    // Market Posts Resource Route
    Route::resource('market', 'MarketPostController');

    // Aircraft controller. Not sure why it's commented out, but now that it is, I'm affraid to uncomment.
    //Route::resource('aircrafts','AircraftController.php');



    //Email Signup Route
    
    Route::post('/emailoptin', 'EmailSignupController@signUp')->name('email.signup');




/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


    Route::auth();

//Route::get('/', 'HomeController@index')->name('home');

    Auth::routes();

    Route::get('/home', 'HomeController@index');

app/Aircraft.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Aircraft extends Model
{
    protected $table = 'aircraft';




public function isPublished(){

	if($this->status == 'publish') {

		return true;

	}

	return false;
}


}

app/Http/Controllers/AircraftController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\Aircraft;
class AircraftController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $aircrafts = Aircraft::all();
      
        return $aircrafts;

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('aircrafts.aircraftscreate')->with('method','post');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        // Validation
        // 
        $this->validate($request, [
        'make' => 'required|max:255',
        'model' => 'required|max:255',
        'serial' => 'required|max:255',
        'tail_number' => 'required|max:255',
        'ex_airline' => 'required|max:255',
    ]);



    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       $aircraft = Aircraft::find($id);

       if($aircraft->isPublished()){

        return view('aircrafts.aircraftsingle')->with('aircraft', $aircraft);

       }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $aircraft = Aircraft::find($id);

       return view('aircrafts.aircraftscreate')->with('method','put')->with('aircraft', $aircraft);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

        public function __construct()
    {
        
    $this->middleware('check_aircraft_approved', ['except' => ['index','show']]);
    }
}

resources/views/aircrafts/aircraftscreate.blade.php
@extends('layouts.master')

@section('content')

 <div class="container">
     <div class="row">
         <div class="col-sm-3">
             <h3>Title area?</h3>
         </div>

         <div class="col-sm-8 col-sm-offset-1">


        <div class="row">

         @if($method == 'post')
{!! Form::open(['method' => 'POST', 'url' => '/aircraft', 'class' => 'form']) !!}


@elseif($method=='put')
{!! Form::model($aircraft, ['route' => ['aircraft.update', $aircraft->id], 'method' => 'PUT', 'class' => 'form']) !!}
@endif

             <div class="panel">
             <div class="panel-body">
<legend>Aircraft Details</legend>
    {{-- Make --}}
             <div class="col-sm-6">
                 <div class="form-group{{ $errors->has('make') ? ' has-error' : '' }}">
                    {!! Form::label('make', 'Manufacturer') !!}
                    {!! Form::text('make', null, ['class' => 'form-control', 'required' => 'required']) !!}
                    <small class="text-danger">{{ $errors->first('make') }}</small>
                </div>
            </div>


    {{-- Model --}}
            <div class="col-sm-6">
                <div class="form-group{{ $errors->has('model') ? ' has-error' : '' }}">
                    {!! Form::label('model', 'Model') !!}
                    {!! Form::text('model', null, ['class' => 'form-control', 'required' => 'required']) !!}
                    <small class="text-danger">{{ $errors->first('model') }}</small>
                </div>
            </div>


    {{-- Serial --}}
            <div class="col-sm-6">
            <div class="form-group{{ $errors->has('serial') ? ' has-error' : '' }}">
                {!! Form::label('serial', 'MSN') !!}
                {!! Form::text('serial', null, ['class' => 'form-control', 'required' => 'required']) !!}
                <small class="text-danger">{{ $errors->first('serial') }}</small>
            </div>
            </div>

    {{-- Tail Number --}}
            <div class="col-sm-6">
                <div class="form-group{{ $errors->has('tail_number') ? ' has-error' : '' }}">
                    {!! Form::label('tail_number', 'Registration / Tail No.') !!}
                    {!! Form::text('tail_number', null, ['class' => 'form-control', 'required' => 'required']) !!}
                    <small class="text-danger">{{ $errors->first('tail_number') }}</small>
                </div>
            </div>

    {{-- Previous Operator / Ex-Airline --}}
            <div class="col-sm-6">

            <div class="form-group{{ $errors->has('ex_airline') ? ' has-error' : '' }}">
                    {!! Form::label('ex_airline', 'Previous Operator') !!}
                    <div class="input-group">
                    <div class="input-group-addon">Ex-</div>
                    {!! Form::text('ex_airline', null, ['class' => 'form-control', 'required' => 'required']) !!}
                    </div>
                    
                    <small class="text-danger">{{ $errors->first('ex_airline') }}</small>
                </div>
            </div>







    {{--   Location --}}

            <div class="col-sm-6">
            <div class="form-group{{ $errors->has('location') ? ' has-error' : '' }}">
                {!! Form::label('location', 'Location') !!}

                {!! Form::textarea('location', null, ['class' => 'form-control', 'required' => 'required', 'rows' => 4]) !!}
                <p class="help-block">Either address, airport, city, etc.</p>
                <small class="text-danger">{{ $errors->first('location') }}</small>
            </div>
            </div>





        </div>
         </div>

             <div class="panel">
             <div class="panel-body">
                <legend>Material Details</legend>


                {{-- Avionics --}}
                <div class="col-sm-12">
                <div class="form-group{{ $errors->has('avionics') ? ' has-error' : '' }}">
                    {!! Form::label('avionics', 'Avionics') !!}
                    {!! Form::textarea('avionics', null, ['class' => 'form-control']) !!}
                    <small class="text-danger">{{ $errors->first('avionics') }}</small>
                </div>
                </div>


                {{-- Engines --}}

                <div class="col-sm-12">
                <div class="form-group{{ $errors->has('engines') ? ' has-error' : '' }}">
                    {!! Form::label('engines', 'Engines') !!}
                    {!! Form::textarea('engines', null, ['class' => 'form-control']) !!}
                    <small class="text-danger">{{ $errors->first('engines') }}</small>
                </div>
                </div>

                {{-- Apu --}}

                <div class="col-sm-12">
                <div class="form-group{{ $errors->has('apu') ? ' has-error' : '' }}">
                        {!! Form::label('apu', 'APU(s)') !!}
                        {!! Form::textarea('apu', null, ['class' => 'form-control', 'required' => 'required']) !!}
                        <small class="text-danger">{{ $errors->first('apu') }}</small>
                    </div>
                </div> 

                {{-- Landing Gear --}}

                <div class="col-sm-12">
                <div class="form-group{{ $errors->has('landing_gear') ? ' has-error' : '' }}">
                        {!! Form::label('landing_gear', 'Landing Gear') !!}
                        {!! Form::textarea('landing_gear', null, ['class' => 'form-control', 'required' => 'required']) !!}
                        <small class="text-danger">{{ $errors->first('landing_gear') }}</small>
                    </div>
                </div>


                {{-- Submit Button --}}
                <div class="col-sm-12">
                    <div class="btn-group pull-right">
                        {!! Form::reset("Reset", ['class' => 'btn btn-warning']) !!}
                        {!! Form::submit("Save", ['class' => 'btn btn-Add']) !!}
                    </div>
                </div>


             </div>
             </div>



        {!! Form::close() !!}
 
 
     </div>

</div>
 </div>

    @endsection

resources/views/aircrafts/aircraftsindex.blade.php
@extends('layouts.master')
@section('stylesheets')
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.css">
@endsection
@section('title','Aircrafts in Tear-down')
@section('content')

	<div class="container">


	<h1>Aircraft</h1>

		<div class="row">
		<div class="col-sm-12">

		 <table id="listings" class="display" cellspacing="0" width="100%">
			<thead>

			<th>Manufacturer</th>
			<th>Model</th>
			<th>Tail No.</th>
			<th>MSN</th>
			<th>Last Operator</th>
			
			<th></th>


			</thead>


			<tbody>
		@foreach($aircrafts as $aircraft)

			<tr>
				<td>{{ $aircraft->make }}</td>
				<td>{{ $aircraft->model }}</td>
				<td>{{ $aircraft->tail_number }}</td>
				<td>{{ $aircraft->serial }}
				<td>{{ $aircraft->ex_airline }}</td>
				<td><a href="{{ route('aircraft.show', $aircraft->id) }}">View</a></td>
			</tr>


		@endforeach
			</tbody>

		</table>

		</div>
		</div>


	</div>



@endsection

resources/views/aircrafts/aircraftsingle.blade.php
@extends('layouts.master')
@section('content')
    @section('title', $aircraft->make .' '. $aircraft->model .' - ' . $aircraft->tail_number . ' - Ex-'.$aircraft->ex_airline )
    <div class="container-fluid jumbotron td-jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-sm-8">
                    <dl class="list-unstyled">
                        
                        <dd><h2>{{ $aircraft->make }} {{ $aircraft->model }}<p></p>

                        <small>Tail Number {{ $aircraft->tail_number }}</small></h2></dd>
                    </dl>

                </div>
                <div class="col-sm-4">
                <h5>Listed by</h5>
                    <div class="media">
                        <div class="media-left">
                            <a href="#">
                                <img class="media-object" src="..." alt="...">
                            </a>
                        </div>
                        <div class="media-body">
                            <h4 class="media-heading">TAG Aero</h4>
                            TAG Aero is the leading manufactuerer of etc..
                            <p></p>
                            <i class="fa fa-phone" aria-hidden="true"></i> +1 407-614-8314 | <i class="fa fa-envelope" aria-hidden="true"></i> info@tag.aero
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
<div class="container">
{{--     @if (Auth::check())
    @if( Auth::user()->id == $aircraft->owned_by )
    <div class="row well">
        <div class="col-sm-6">
           <h4>This is your listing. It will expire in {{ $aircraft->days_to_go }} days.</h4>
        </div>
        <div class="col-sm-6">
            <a href="{{ route('aircraft.edit', $aircraft->id) }}" class="btn btn-default pull-right">Edit</a>
        </div>
    </div>
    @endif
    @endif --}}



    <div class="row">


    <div class="col-sm-12">

        <div class="panel panel-default">

            <div class="panel-heading">
                <strong>Engines</strong>
            </div>

            <div class="panel-body">           
                 <dl class="dl-horizontal">

                    <dt>Make</dt>
                    <dd>{{ $aircraft->make }}</dd>

                    <dt>Model</dt>
                    <dd>{{ $aircraft->model }}</dd>

                    <dt>Serial Number</dt>
                    <dd>{{ $aircraft->serial }}</dd>
                
                   
                </dl>
            </div>

        </div>
        </div>





            <div class="col-sm-12">


        <div class="panel panel-default">

            <div class="panel-heading">
                <strong>Engines</strong>
            </div>

            <div class="panel-body">           
                    <p>
                    {{ $aircraft->engines }}
                    </p>
            </div>

        </div>

            </div>


            <div class="col-sm-12 ">
                
              <div class="panel panel-default">

            <div class="panel-heading">
                <strong>APUs</strong>
            </div>

            <div class="panel-body">           
                    <p>
                    {{ $aircraft->apu }}
                    </p>
            </div>

        </div>
            </div>


            <div class="col-sm-12">
                
                       <div class="panel panel-default">

            <div class="panel-heading">
                <strong>Avionics</strong>
            </div>

            <div class="panel-body">           
                    <p>
                    {{ $aircraft->avionics }}
                    </p>
            </div>

        </div>


            </div>

            <div class="col-sm-12 ">
                
               <div class="panel panel-default">

            <div class="panel-heading">
                <strong>Landing Gear</strong>
            </div>

            <div class="panel-body">           
                    <p>
                    {{ $aircraft->landing_gear }}
                    </p>
            </div>

        </div>


            </div>

</div>


        </div>



@endsection