routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
use App\Notifications\ExpirationWarning;

    // Home Page route

    // Route::get('/', function () {





    //         return route('page.home');


    // })->name('home');









    /**
     *
     *  AUTH MIDDLEWARE
     *
     *
     */


    Route::group(['middleware' => 'auth'], function () {

        // All my routes that needs a logged in user
        Route::get('/checkout', 'NewListingsController@showPaymentForm')->name('paymentform');

        // Dashboard Routes
        Route::get('dashboard', 'DashboardController@index')->name('dashboard');

        // Shows order history
        Route::get('dashboard/billing/', 'DashboardController@billing')->name('dashboard.billing');

        // Displays the listings management - Note: This will be changed to new routes for each listing type.
        Route::get('dashboard/listings', 'DashboardController@listings')->name('dashboard.listings');


                /**
                 *  Credit Card Stripe Routes
                 */
        
                // AJAX route for CCs
                Route::get('dashboard/ccAjax', 'DashboardController@ccAjax')->name('dashboard.ccAjax');
                
                // Route to handle setting stripe default
                Route::post('dashboard/newdefault', 'DashboardController@setNewDefault')->name('dashboard.newDefault');
                
                // Add a credit card
                Route::post('dashboard/addcreditcard', 'DashboardController@addCreditCard')->name('dashboard.addCreditCard');

                // Delete Credit Cards
                Route::post('dashboard/deletecard', 'DashboardController@deleteCard')->name('dashboard.deleteCard');


        // Show invoices
        Route::get('dashboard/invoices', 'DashboardController@invoices')->name('dashboard.invoices');

        // Route to download an invoice by ID
        Route::get('/dashboard/invoices/download/{id}', 'InvoiceController@download')->name('dashboard.billing.download');

                /**
                 *
                 * User Profile Routes
                 *
                 */

                //Show user profile
                Route::get('dashboard/profile', 'DashboardController@profile')->name('dashboard.profile');
                
                // Update user data
                Route::post('dashboard/profile/update', 'DashboardController@updateUser')->name('dashboard.updateuser');

                // Remove the avatar file route
                Route::get('dashboard/profile/removeavatar', 'DashboardController@removeAvatar')->name('dashboard.removeavatar');


        // Show notifications
        Route::get('dashboard/notifications', 'DashboardController@messages')->name('dashboard.messages');

        // Messages controller
        Route::resource('message', 'MessageController');

        Route::get('dashboard/membership', 'DashboardController@membership')->name('dashboard.membership');
        Route::post('dashboard/membership/cancel/process', 'DashboardController@cancelSubscription')->name('dashboard.membership.cancel');

            /**
             *  Active Search Routes - Note: This is still in alpha stage. Not operational at this time.
             */
            
            // Route::get('dashboard/activesearch','DashboardController@activesearch')->name('dashboard.activesearch');
            // Route::post('dashboard/activesearch/create','DashboardController@activeSearchCreate')->name('dashboard.activesearchcreate');

        // Orders Resource
        Route::resource('orders', 'OrderController');
        // Route::resource('apus', 'MessageController');

        // Aircraft Resource 
        Route::resource('aircraft', 'AircraftController');

        //Read Message Post - Note: This is a legacy AJAX handler
        Route::post('dashboard/message/read', 'MessageController@readMessage');

        // Invoices Resource
        Route::resource('invoices', 'InvoiceController@index');

        // Favorite Resource <3
        Route::resource('favorite', 'FavoritesController@index');

       // Page Resource
        Route::resource('page', 'PageController');

        // Home page
        Route::get('/', 'PageController@home')->name('home');



        // New Listings Routes
        Route::get('/new', 'NewListingsController@index')->name('newlisting');
        Route::get('/new/apu', 'NewListingsController@apu')->name('newapulisting');
    });




    /**
     *
     *      STRIPE
     *
     *      Note: This runs through a second middleware called a stripe_check, which ensures the user has a default payment method set up before *      completing
     *
     */



    // Show checkout page
    Route::get('/checkout', 'NewListingsController@showPaymentForm')->name('paymentform')->middleware('auth', 'stripe_check');

    // Process Payment
    Route::post('/checkout/process', 'NewListingsController@processPayment')->name('processpayment')->middleware('auth', 'stripe_check');

    // Show Upgrade Page
    Route::get('dashboard/membership/upgrade', 'DashboardController@showUpgrade')->name('dashboard.membership.showupgrade')->middleware('auth', 'stripe_check');

    // Process Membership Upgrade
    Route::post('dashboard/membership/upgrade/process', 'DashboardController@processUpgrade')->name('dashboard.membership.processupgrade')->middleware('auth', 'stripe_check');




    // STRIPE WEBHOOK LISTENER - Note: This receives all requests from Stripe
    Route::post('stripe/webhook', 'StripeController@handleWebHook');



    /**
     *    /END STRIPE
     */




    // Search Results
    Route::get('search', 'SearchController@search')->name('search');

    // Log out
    Route::get('/logout', function () {

        Auth::logout();
        return redirect('/login')->with('success', 'successfully logged out');
    })->name('logout');


    // APU Resource Route - Note: This needs to be changed to partial routes, for auth purposes.
    Route::resource('apus', 'ApuController');

    // Engine Resource Route - Note: Ditto above.
    Route::resource('engines', 'EngineController');

    // Legacy Market routes that I may still use
    Route::get('market/ajax', 'MarketPostController@marketAjax');

    // Market Posts Resource Route
    Route::resource('market', 'MarketPostController');

    // Aircraft controller. Not sure why it's commented out, but now that it is, I'm affraid to uncomment.
    //Route::resource('aircrafts','AircraftController.php');



    //Email Signup Route
    
    Route::post('/emailoptin', 'EmailSignupController@signUp')->name('email.signup');




/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


    Route::auth();

//Route::get('/', 'HomeController@index')->name('home');

    Auth::routes();

    Route::get('/home', 'HomeController@index');

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Apu;
use App\Invoice;
use App\User;
use App\Engine;
use App\MarketPost;
use Illuminate\Http\Request;
use Validator;
use Input;
use Redirect;
use Auth;
use App\Order;
use DB;
use Illuminate\Http\Response;
use Cartalyst\Stripe\Stripe;
use Carbon\Carbon;
use Illuminate\Support\Facades\Storage;
use Image;
use App\Http\Requests;
use Illuminate\Support\Facades\View;
use App\Message;
use App\ActiveSearch;
use Illuminate\Support\Facades\Cache;

use Mailgun\Mailgun;

class DashboardController extends Controller
{



    public function index()
    {
//        $stripe = new Stripe(env('STRIPE_SECRET'));

        $user = Auth::user();

//        $customer = $stripe->customers()->find($user->stripe_id);
        return view('dashboard.profile')->with('user', $user);
    }





    public function billing()
    {

        /*
         *
         *  PAYMENT OPTIONS MANAGEMENT
         *
         */


        // Get user object
        $user = Auth::user();

        // If user has stripe id already
        if ($user->hasStripeId() and $user->hasDefaultCard()) {
            //Initialize
            $stripe = new Stripe(env('STRIPE_SECRET'));


            // Retreive all cards
            $cards = $stripe->cards()->all($user->stripe_id);
            $customer = $stripe->customers()->find($user->stripe_id);

            // Return view with $card array
            return view('dashboard.billing')->with('cards', $cards)->with('customer', $customer)->with('hasStripe', true);
        }


        // Return view with $card array
        return view('dashboard.billing')->with('hasStripe', false);
    }






    function addCreditCard(Request $request)
    {

        //Initialize
        $stripe = new Stripe(env('STRIPE_SECRET'));

        // Get user object
        $user = Auth::user();
        
        
        
        if ($user->hasStripeId()) {
            $card = $stripe->cards()->create($user->stripe_id, $request->stripeToken);

            if ($request->session()->has('inbound_url')) {
                return redirect($request->session()->get('inbound_url'));
            } else {
                return redirect()->back();
            }
        }

            $user->stripe_id = $newCustomer['id'];

            $user->save();


        if ($request->session()->has('inbound_url')) {
            return redirect($request->session()->get('inbound_url'));
        } else {
            return redirect()->back();
        }
    }


    

    function setNewDefault(Request $request)
    {

        $user = Auth::user();
        // load in the data

        // Get user's stripe object
        \Stripe\Stripe::setApiKey("sk_test_QnrOrUxY0S43c6GEhiu9Nwhe");

        $customer = \Stripe\Customer::retrieve($user->stripe_id);
        $customer->default_source = $request->newDefault;
        $customer->save();

        return redirect('/dashboard/billing');
    }

    function deleteCard(Request $request)
    {

        $user = Auth::user();
        // load in the data

        // Get user's stripe object
        \Stripe\Stripe::setApiKey("sk_test_QnrOrUxY0S43c6GEhiu9Nwhe");

        $customer = \Stripe\Customer::retrieve($user->stripe_id);
        $customer->sources->retrieve($request->deleteID)->delete();

        return redirect('/dashboard/billing');
    }

    public function invoices()
    {

        /*
         *
         *  Show invoices
         *
         */

        // Get user object
        $user = Auth::user();

        $invoices = $user->invoices()->latest()->get();


        if (!$invoices== null) {
            return view('dashboard.invoices')
                ->with('invoices', $invoices)
                ->with('user', $user);
        } else {
            return view('dashboard.invoices')
            ->with('user', $user);
        }
    }


    public function listings()
    {

        /*
         *
         * Manage Listings
         *
         */

        $user = Auth::user();

        $engines = $user->engines()->where('days_to_go', '>', 0)->get();
        $apus = $user->apus()->get();
        $marketPosts = $user->marketPosts()->take(10)->get();
        return view('dashboard.listings')

            ->with('engines', $engines)
            ->with('apus', $apus)
            ->with('marketPosts', $marketPosts);
    }

    public function profile()
    {

        /*
         *
         * Show Profile Page
         *
         */

        $user = Auth::user();
        return view('dashboard.profile')->with('user', $user);
    }

    public function updateUser(Request $request)
    {

        /*
		 *
		 * Used to update user at profile page
		 *
		 */
        Cache::flush();

        $validator = Validator::make($request->all(), [
            'avatar' => 'image|mimes:jpeg,jpg'
        ]);
        if ($validator->fails()) {
            return redirect()->back();
        }


        $user = Auth::user();

        $user->name = $request->input('name');
        $user->email = $request->input('email');
        $user->phone_number = $request->input('phone_number');


        /*
         * Email list management with mailgun
         */



        # Instantiate the client.
        $mgClient = new Mailgun(env('MAILGUN_SECRET'));
        $listMember = $user->email;
        $memberAddress = $user->email;
        $dailyAddress = env('MAILGUN_DAILY_ADDRESS');
        $weeklyAddress = env('MAILGUN_WEEKLY_ADDRESS');

        
        if ($request->input('daily_email')) {
            // add user to mailing list

            $result = $mgClient->post("lists/$dailyAddress/members", [
                'address' => $user->email,
                'name' => $user->name,
                'subscribed' => true,
                'upsert' => 'yes'
            ]);
        } elseif (!$request->input('daily_email')) {
            if ($user->daily_email == true) {
                $result = $mgClient->delete("lists/$dailyAddress/members/$listMember");
            }
        }


        if ($request->input('weekly_email')) {
            $result = $mgClient->post("lists/$weeklyAddress/members", [
            'address' => $user->email,
            'name' => $user->name,
            'subscribed' => true,
            'upsert' => 'yes'
            ]);
        } elseif (!$request->input('weekly_email')) {
            if ($user->weekly_email == true) {
                $result = $mgClient->delete("lists/$weeklyAddress/members/$listMember");
            }
        }

            // DAILY EMAIL LIST
            $user->daily_email = $request->input('daily_email');

            // WEEKLY EMAIL LIST
            $user->weekly_email = $request->input('weekly_email');


            $user->position = $request->input('position');
            $user->company = $request->input('company');


            // AVATAR
        if ($request->hasFile('avatar')) {
            $directory = 'public/avatars/' . $request->user()->id . '/';

              

               
            $files = Storage::files($directory);
            Storage::delete($files);

            $image = Image::make($request->file('avatar'))->fit(200, 140)->save();
            $path = Storage::put('public/avatars/' . $request->user()->id . '/' . $request->user()->id . '.jpg', $image);

            $user->avatar = $path;
        }

            $user->save();
            Cache::flush();

            return View::make('dashboard.profile')->with('user', $user)->render();
    }

    

    public function removeAvatar(Request $request)
    {

        $user = Auth::user();

        $user->avatar = null;

        $user->save();

        Storage::delete('public/avatars/' . $user->id . '/' . $user->id . '.jpg');

        return redirect()->back();
    }


    public function messages()
    {
        /*
         *
         * Show messages inbox (called "notifications" for now)
         *
         */
        $user = Auth::user();



        $msgs = $user->messages()->latest()->paginate(15);

        // $messages = Message::where('user_id', '==', $user->id)->paginate(15);



        return view('dashboard.messages')
                ->with('msgs', $msgs);
    }

    public function membership()
    {
        /*
         *
         * Show membership panel
         *
         */


        //Initialize
        $stripe = new Stripe(env('STRIPE_SECRET'));

        // Get user object
        $user = Auth::user();

        if ($user->hasStripeId()) {
            $customer = $stripe->customers()->find($user->stripe_id);

            $subscription = $customer['subscriptions'];

            if ($user->isPremium()) {
                return view('dashboard.membership')->with('sub', $subscription['data']['0']);
            } else {
                return view('dashboard.membership');
            }
        } else {
            return view('dashboard.membership');
        }
    }




    public function activesearch()
    {


        $user = Auth::user();
        $searches = $user->activeSearches()->get();
        $ActiveSearch = ActiveSearch::find(1);

        return view('dashboard.activesearch')->with('ActiveSearch', $ActiveSearch);
    }


    public function showUpgrade()
    {
        /*
         *
         * Show the upgrade confirmation page
         *
         */


        // Get user's stripe object
        \Stripe\Stripe::setApiKey(env('STRIPE_SECRET'));

        // Get user object
        $user = Auth::user();

        if (!$user->isPremium()) {
            $customer = \Stripe\Customer::retrieve($user->stripe_id);

            return view('dashboard.membershipupgrade')->with('customer', $customer)->with('total', 49999);
        } else {
            return redirect()->route('dashboard.membership');
        }
    }

    public function processUpgrade(Request $request)
    {
        /*
         *
         * Process the membership upgrade
         * This thing is a cluster fuck. I really need to refactor this.
         */

        //Initialize
        $stripe = new Stripe(env('STRIPE_SECRET'));

resources/views/dashboard/activesearch.blade.php
@extends('dashboard.dashboardmaster')


@section('admincontent')

    <div class="panel panel-default">
        <div class="panel-heading">ActiveSearch™</div>
        <div class="col-xs-12">


            {{ var_dump($ActiveSearch->searchParameters()->get()) }}



            {{--{!! Form::open([--}}

            {{--'url' => 'dashboard/activesearch/create',--}}
            {{--'class'=>'activesearch-form',--}}
            {{--'data-parsley-validate',--}}
            {{--'method'=>'post']--}}


    {{--) !!}--}}
            {{--{{ Form::model($ActiveSearch) }}--}}

            {{--<?php--}}

            {{--$params = $ActiveSearch->params;--}}

            {{--?>--}}

            {{--@foreach($params as $key=>$value)--}}
                {{--<?php  $inputNumber = array_search($key, array_keys($ActiveSearch->params)); ?>--}}


            {{--<div class="form-group">--}}

                {{--{{ Form::select("key_'.$inputNumber.'", [--}}
                    {{--'model'=>'Model',--}}
                    {{--'serial'=>'Serial',--}}
                    {{--'part_number' => 'Part Number',--}}
                    {{--'condition' => 'Condition'--}}
                {{--], $key ) }}--}}

            {{--</div>--}}
                {{--<div class="form-group">--}}
                    {{--{{ Form::text("value_'.$inputNumber.'", $value) }}--}}
                {{--</div>--}}
                {{--<hr>--}}
            {{--@endforeach--}}



















    {{--@if($ActiveSearch->params = null)--}}

    {{--{{ Form::select('key', null) }}--}}

    {{--@elseif(!$ActiveSearch == null)--}}

        {{--@foreach($ActiveSearch->params as $key=>$value)--}}


                 {{--@if(!array_key_exists($key, $ActiveSearch->params))--}}

                 {{--{{ $inputNumber = array_search($key, array_keys($ActiveSearch->params)) }}--}}



                    {{--@if($key == 'condition'or $key == 'trace')--}}


                        {{--@if($key=='condition')--}}

                            {{--<?php--}}
                                {{--$choices = [--}}

                                    {{--'AR' => 'AR',--}}
                                    {{--'SV' => 'SV',--}}
                                    {{--'OH' => 'OH',--}}
                                    {{--'NE' => 'NE',--}}
                                    {{--'NS' => 'NS'--}}
                                {{--]--}}

                            {{--?>--}}
                            {{--@elseif($key=='trace')--}}

                                {{--<?php--}}
                                {{--$choices = [--}}

                                        {{--'121' => '121 Operator',--}}
                                        {{--'129' => '129 Operator',--}}
                                        {{--'135'=>'135 Operator',--}}
                                        {{--'145'=>'145 Repair Station',--}}
                                        {{--'OEM'=>'OEM',--}}
                                        {{--'Foreign'=>'Foreign Operator',--}}
                                        {{--'NA'=>'N/A']--}}

                                {{--?>--}}


                            {{--@endif--}}

                    {{--{{ Form::select("param_'.$inputNumber.'", $choices,--}}
                     {{--null, ['placeholder' => 'Select', 'class'=>'form-control']) }}--}}

                        {{--@else--}}


                            {{--{{ Form::text("param_'.$inputNumber.'", null) }}--}}

                        {{--@endif--}}
{{--@endif--}}
        {{--@endforeach--}}




    {{--@endif--}}




            {!! Form::close() !!}
        </div>



        <table class="table">
            <thead>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Username</th>
            </tr>
            </thead>
            <tbody>



            </tbody>
        </table>
    </div>











@endsection

resources/views/dashboard/addsource.blade.php
@extends('auth.authmaster')


@section('content')



    @include('dashboard.partials.sections._billingnewcard')


    @endsection

resources/views/dashboard/billing.blade.php
@extends('dashboard.dashboardmaster')

@section('title')
    Dashboard - Billing Options
@endsection




@section('admincontent')


    @if(session('inbound_url_message'))

        <div class="alert-success alert"> {{ session('inbound_url_message') }}</div>

        @endif



    @if($hasStripe)


    <div class="row" style="margin-bottom:20px;">

        <div class="col-sm-8">
            @if(isset($message))

                <div class="panel-success panel"> {{ $message }}</div>


                @endif
        </div>


        <div class="col-sm-4">

            <a href="#" class="btn btn-primary pull-right" data-toggle="modal" data-target="#new_card">Add New Card</a>
            <!-- Modal -->
            <div id="new_card" class="modal fade" role="dialog">
                <div class="modal-dialog">

                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Add New Card</h4>
                        </div>

                           @include('dashboard.partials.sections._billingnewcard')

                    </div>

                </div>
            </div>
        </div>
        <br>
    </div>

@endif

    <div class="panel panel-default">


        <div class="panel-heading">
            <strong>Billing Options</strong>
        </div>

        <div class="panel-body">


            @if(!$hasStripe)

                @include('dashboard.partials.sections._billingnewcard')

                @else

                @include('dashboard.partials.sections._billingoptions')


                @endif

        </div>
    </div>

@endsection

@section('stylesheets')
    <input type="hidden" id="STRIPE_KEY" value="{{ env('STRIPE_KEY') }}"/>
    <script type="text/javascript">


        var StripeKey = $('#STRIPE_KEY').val();
        console.log(StripeKey);

    </script>

    <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
    {{ Html::script('src/js/dashboard.js') }}
@endsection

resources/views/dashboard/dashboardmaster.blade.php
@extends('layouts.master')
@section('title')
    Dashboard
    @endsection

@section('content')
    <div class="container">
        <div class="row row-offcanvas row-offcanvas-left">
            {{--SIDE NAV BAR--}}
<div class="sidebar-loader">
    @include('dashboard.partials._adminsidebar')
</div>



            <div class="col-xs-12 col-sm-9 content">
                @if(isset($message))

                    <div class="panel-success panel"> {{ $message }}</div>


                @endif


               @yield('admincontent')
            </div><!-- content -->
        </div>
    </div>
    @endsection

resources/views/dashboard/invoices.blade.php
@extends('dashboard.dashboardmaster')


@section('admincontent')
    <div class="panel panel-default">
        <div class="panel-heading">
            <strong>Order History</strong>
        </div>

        <div class="panel-body">

            @if(isset($invoices))
    @include('dashboard.partials.sections._invoices')

                @else
            <p class="text-center">No invoices have been created at this time.</p>
            @endif
        </div>
    </div>

@endsection

resources/views/dashboard/listings.blade.php
@extends('dashboard.dashboardmaster')


@section('admincontent')

    <div class="row">
        <div class="col-xs-12">
            <h5>My Listings</h5>
        </div>

    </div>


<div class="panel">
    <ul id="myTab1" class="nav nav-tabs nav-justified">
        <li class="active"><a href="#engines" data-toggle="tab">Engines</a></li>
        <li class=""><a href="#apus" data-toggle="tab">APUs</a></li>
        <li class=""><a href="#aircraft" data-toggle="tab">Aircraft</a></li>
        <li class=""><a href="#market" data-toggle="tab">Market</a></li>


    </ul>
    <div id="myTabContent" class="tab-content">
        <div class="tab-pane fade active in" id="engines">

            @include('dashboard.partials.sections._listings',['units'=>$engines])

        </div>
        <div class="tab-pane fade" id="apus">
            @include('dashboard.partials.sections._listings',['units'=>$apus])
        </div>
        <div class="tab-pane fade" id="aircraft">
     Planes n shit
        </div>
        <div class="tab-pane fade" id="market">
           @foreach($marketPosts as $marketPost)


                  <p> <strong>{{ $marketPost->market_title }}</strong></p>
                   <p>{{ $marketPost->market_body }}</p>
                   <p> <small><em>Posted on {{ Carbon::createFromTimestamp(strtotime($marketPost->created_at))->toFormattedDateString() }}</em>
                           {{ Form::open(array('route' => array('market.destroy', $marketPost->id), 'method' => 'delete')) }}
                           <button type="submit" class="btn btn-default btn-xs">Delete</button>
                           {{ Form::close() }}
                       </small> </p>

<hr>

               @endforeach
        </div>


    </div>
</div>




    @endsection

resources/views/dashboard/membership.blade.php
@extends('dashboard.dashboardmaster')


@section('admincontent')



    <div class="panel panel-default">
        <div class="panel-heading"><strong>Membership</strong></div>
        <div class="panel-body">


            @if(isset($sub))

                @include('dashboard.partials.sections._membershippremium')

                @else

                @include('dashboard.partials.sections._membershippleb')

            @endif



        </div>
    </div>

    @endsection

resources/views/dashboard/membershipupgrade.blade.php
@extends('dashboard.dashboardmaster')



@section('admincontent')

    <div class="panel panel-default">
        <div class="panel-heading">Upgrade Confirmation</div>
        <div class="panel-body">

            <div class="col-sm-4">
<?php
                // Access card information
                $defaultID = $customer->default_source;
                $default = $customer->sources->retrieve($defaultID);

                $sources = $customer->sources->all(array(
                'object' => 'card'));

                ?>



                    {!! Form::open([

                            'url' => 'dashboard/membership/upgrade/process',
                            'class'=>'payment-form',
                            'method'=>'post']


                    ) !!}
                    <div class="form-group">
                        <label>Payment Method:</label>
                        <select name="card_id" class="form-control">
                            <option value="{{ $default->id }}" selected>(default) {{ $default->brand }} - ({{ $default->last4 }})</option>

                            @foreach($customer->sources->data as $source)
                                @if($source->id !== $default->id)

                                    <option value="{{ $source->id }}">{{ $source->brand }} - ({{ $source->last4 }})</option>

                                @endif
                            @endforeach

                        </select>
                        <p></p>
                        <p class="text-right"><small><a href="#">Manage Payment Options</a></small></p>

                    </div>

                    <hr>
                    <h3 class="text-center">${{ $total/100 }}</h3>
                    <p class="text-center">Per Month</p>

                    {{ Form::submit('Complete Purchase', ['class'=>'btn btn-primary btn-lg btn-block']) }}



                    {!! Form::close() !!}








            </div>

            <div class="col-sm-8">

                <h3>Order Summary</h3>
                <table class="table">
                    <thead>
                    <tr>
                        <th>Desc</th>

                        <th>Total</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>Teardown.Aero Premium Membership</td>
                        <td>${{ $total / 100 }} / mo.</td>

                    </tr>

                    </tbody>
                </table>
            </div>






        </div>
    </div>


    @endsection

resources/views/dashboard/messages.blade.php
@extends('dashboard.dashboardmaster')

@section('stylesheets')
    {{ Html::script('src/js/messages.js') }}
    @endsection
@section('admincontent')


    <div class="messages-content-loader">
       

    	<div class="list-group">

    @foreach($msgs as $msg)
        <a href="{{ route('message.show', $msg->id) }}"  class=" list-group-item">
            <!-- Modal -->



            @if($msg->unread == true)

                <span class="label label-success">New</span> <strong>{{ $msg->subject }} <small>(Unread)</small></strong>

            @else

                {{ $msg->subject }}

            @endif



            <span class="pull-right">{{ $msg->created_at }}</span>



        </a>
        <div data-read = "{{ $msg->unread }}" data-message-id = "{{ $msg->id }}" class="modal td-message-modal fade" id="message_{{ $msg->id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">{{ $msg->subject }}</h4>
                    </div>
                    <div class="modal-body">
                        <p>{{ $msg->body }}</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>

    @endforeach



    
</div>
{{ $msgs->render() }}




    </div>
  
    @endsection