routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
use App\Notifications\ExpirationWarning;

    // Home Page route

    // Route::get('/', function () {





    //         return route('page.home');


    // })->name('home');









    /**
     *
     *  AUTH MIDDLEWARE
     *
     *
     */


    Route::group(['middleware' => 'auth'], function () {

        // All my routes that needs a logged in user
        Route::get('/checkout', 'NewListingsController@showPaymentForm')->name('paymentform');

        // Dashboard Routes
        Route::get('dashboard', 'DashboardController@index')->name('dashboard');

        // Shows order history
        Route::get('dashboard/billing/', 'DashboardController@billing')->name('dashboard.billing');

        // Displays the listings management - Note: This will be changed to new routes for each listing type.
        Route::get('dashboard/listings', 'DashboardController@listings')->name('dashboard.listings');


                /**
                 *  Credit Card Stripe Routes
                 */
        
                // AJAX route for CCs
                Route::get('dashboard/ccAjax', 'DashboardController@ccAjax')->name('dashboard.ccAjax');
                
                // Route to handle setting stripe default
                Route::post('dashboard/newdefault', 'DashboardController@setNewDefault')->name('dashboard.newDefault');
                
                // Add a credit card
                Route::post('dashboard/addcreditcard', 'DashboardController@addCreditCard')->name('dashboard.addCreditCard');

                // Delete Credit Cards
                Route::post('dashboard/deletecard', 'DashboardController@deleteCard')->name('dashboard.deleteCard');


        // Show invoices
        Route::get('dashboard/invoices', 'DashboardController@invoices')->name('dashboard.invoices');

        // Route to download an invoice by ID
        Route::get('/dashboard/invoices/download/{id}', 'InvoiceController@download')->name('dashboard.billing.download');

                /**
                 *
                 * User Profile Routes
                 *
                 */

                //Show user profile
                Route::get('dashboard/profile', 'DashboardController@profile')->name('dashboard.profile');
                
                // Update user data
                Route::post('dashboard/profile/update', 'DashboardController@updateUser')->name('dashboard.updateuser');

                // Remove the avatar file route
                Route::get('dashboard/profile/removeavatar', 'DashboardController@removeAvatar')->name('dashboard.removeavatar');


        // Show notifications
        Route::get('dashboard/notifications', 'DashboardController@messages')->name('dashboard.messages');

        // Messages controller
        Route::resource('message', 'MessageController');

        Route::get('dashboard/membership', 'DashboardController@membership')->name('dashboard.membership');
        Route::post('dashboard/membership/cancel/process', 'DashboardController@cancelSubscription')->name('dashboard.membership.cancel');

            /**
             *  Active Search Routes - Note: This is still in alpha stage. Not operational at this time.
             */
            
            // Route::get('dashboard/activesearch','DashboardController@activesearch')->name('dashboard.activesearch');
            // Route::post('dashboard/activesearch/create','DashboardController@activeSearchCreate')->name('dashboard.activesearchcreate');

        // Orders Resource
        Route::resource('orders', 'OrderController');
        // Route::resource('apus', 'MessageController');

        // Aircraft Resource 
        Route::resource('aircraft', 'AircraftController');

        //Read Message Post - Note: This is a legacy AJAX handler
        Route::post('dashboard/message/read', 'MessageController@readMessage');

        // Invoices Resource
        Route::resource('invoices', 'InvoiceController@index');

        // Favorite Resource <3
        Route::resource('favorite', 'FavoritesController@index');

       // Page Resource
        Route::resource('page', 'PageController');

        // Home page
        Route::get('/', 'PageController@home')->name('home');



        // New Listings Routes
        Route::get('/new', 'NewListingsController@index')->name('newlisting');
        Route::get('/new/apu', 'NewListingsController@apu')->name('newapulisting');
    });




    /**
     *
     *      STRIPE
     *
     *      Note: This runs through a second middleware called a stripe_check, which ensures the user has a default payment method set up before *      completing
     *
     */



    // Show checkout page
    Route::get('/checkout', 'NewListingsController@showPaymentForm')->name('paymentform')->middleware('auth', 'stripe_check');

    // Process Payment
    Route::post('/checkout/process', 'NewListingsController@processPayment')->name('processpayment')->middleware('auth', 'stripe_check');

    // Show Upgrade Page
    Route::get('dashboard/membership/upgrade', 'DashboardController@showUpgrade')->name('dashboard.membership.showupgrade')->middleware('auth', 'stripe_check');

    // Process Membership Upgrade
    Route::post('dashboard/membership/upgrade/process', 'DashboardController@processUpgrade')->name('dashboard.membership.processupgrade')->middleware('auth', 'stripe_check');




    // STRIPE WEBHOOK LISTENER - Note: This receives all requests from Stripe
    Route::post('stripe/webhook', 'StripeController@handleWebHook');



    /**
     *    /END STRIPE
     */




    // Search Results
    Route::get('search', 'SearchController@search')->name('search');

    // Log out
    Route::get('/logout', function () {

        Auth::logout();
        return redirect('/login')->with('success', 'successfully logged out');
    })->name('logout');


    // APU Resource Route - Note: This needs to be changed to partial routes, for auth purposes.
    Route::resource('apus', 'ApuController');

    // Engine Resource Route - Note: Ditto above.
    Route::resource('engines', 'EngineController');

    // Legacy Market routes that I may still use
    Route::get('market/ajax', 'MarketPostController@marketAjax');

    // Market Posts Resource Route
    Route::resource('market', 'MarketPostController');

    // Aircraft controller. Not sure why it's commented out, but now that it is, I'm affraid to uncomment.
    //Route::resource('aircrafts','AircraftController.php');



    //Email Signup Route
    
    Route::post('/emailoptin', 'EmailSignupController@signUp')->name('email.signup');




/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


    Route::auth();

//Route::get('/', 'HomeController@index')->name('home');

    Auth::routes();

    Route::get('/home', 'HomeController@index');

app/Http/Controllers/NewListingsController.php
<?php

namespace App\Http\Controllers;

use App\Events\ListingsPurchased;
use App\Invoice;
use App\Notifications\ListingConfirmationNotification;
use Illuminate\Http\Request;
use Validator;
use Input;
use Redirect;
use App\Http\Requests;
use App\Apu;
use Auth;
use Carbon\Carbon;
use App\Order;
use App\Message;

use App\Mail\NewListingsPurchaseEmail;

class NewListingsController extends Controller
{
    public function index()
    {

        return view('newlistings.newlistingselect');
    }

    public function apu()
    {

        $apus = Apu::all();
        $engines = Engine::all();
        return view('newlistings.newlistingcreator')
            ->with('type', 'apu')
            ->with('apus', $apus)
            ->with('engines', $engines);
    }

    public function viewCheckout($cart)
    {
    }


    public function processPayment(Request $payment)
    {

        

        // SET VARIABLES
        $user = Auth::user(); // Get User
        \Stripe\Stripe::setApiKey(env('STRIPE_SECRET')); // Set API Key
        $customer = \Stripe\Customer::retrieve($user->stripe_id); // Get Customer object

        // Get unpaid APUs
        $apus = $user->apus()->where('status', '=', 'draft')->get();

        // Get unpaid Engines
        $engines = $user->engines()->where('status', '=', 'draft')->get();


        // Create the empty array to fill with lines
        $lines = [];

        if ($user->isPremium()) {
            $apuPrice = 0;
            $enginePrice = 0;
        } else {
            $apuPrice = config('stripe.apu.price');
            $enginePrice = config('stripe.engine.price');
        }





        // Create APU line items
        if (!$apus->isEmpty()) {
            foreach ($apus as $apu) {
                \Stripe\InvoiceItem::create([
                        "customer" => $customer->id,
                        "amount" => $apuPrice,
                        "currency" => "usd",
                        "description" => ''. $apu->model . ' SN ' . $apu->serial . ' Listing']);
            }
        }

        // Create Engine line items
        if (!$engines->isEmpty()) {
            foreach ($engines as $engine) {
                \Stripe\InvoiceItem::create([
                        "customer" => $customer->id,
                        "amount" => $enginePrice,
                        "currency" => "usd",
                        "description" => ''. $engine->model . ' ESN ' . $engine->serial . ' Listing']);
            }
        }


        // // Create invoice here
        // $invoice = \Stripe\Invoice::create(array(
        // 	"customer" => $customer->id
        // ));




/*
*	TRY / CATCH 
	From stripe
*
*
*/




        try {
                // Create invoice here
                $invoice = \Stripe\Invoice::create([
            "customer" => $customer->id
                ]);

                        $invoice->pay();
        } catch (\Stripe\Error\Card $e) {
                  // Since it's a decline, \Stripe\Error\Card will be caught
                  $body = $e->getJsonBody();
                  $err  = $body['error'];

                  print('Status is:' . $e->getHttpStatus() . "\n");
                  print('Type is:' . $err['type'] . "\n");
                  print('Code is:' . $err['code'] . "\n");
                  // param is '' in this case
                  print('Param is:' . $err['param'] . "\n");
                  print('Message is:' . $err['message'] . "\n");
        } catch (\Stripe\Error\RateLimit $e) {
                  // Too many requests made to the API too quickly
        } catch (\Stripe\Error\InvalidRequest $e) {
                  // Invalid parameters were supplied to Stripe's API
        } catch (\Stripe\Error\Authentication $e) {
                  // Authentication with Stripe's API failed
                  // (maybe you changed API keys recently)
        } catch (\Stripe\Error\ApiConnection $e) {
                  // Network communication with Stripe failed
        } catch (\Stripe\Error\Base $e) {
                  // Display a very generic error to the user, and maybe send
                  // yourself an email
        } catch (Exception $e) {
                  // Something else happened, completely unrelated to Stripe
        }



        return view('newlistings.paymentconfirmation')
            ->with('apus', $apus)
            ->with('engines', $engines);
    }
    
    public function showPaymentForm()
    {



        if (Auth::user()->hasUnpublished()) {
            $total = 0;

            $user = Auth::user();
            \Stripe\Stripe::setApiKey(env('STRIPE_SECRET'));
            $customer = \Stripe\Customer::retrieve($user->stripe_id);

            // APUs
            $apus = Auth::user()->apus()->where('status', '=', 'draft')->get();
            $apuPrice = config('stripe.apu.price');

            $engines = Auth::user()->engines()->where('status', '=', 'draft')->get();
            $enginePrice = config('stripe.engine.price');

            if ($apus) {
                $apuCount = $apus->count();
                $apuTotal = $apuCount * $apuPrice;
            } else {
                $apuTotal = 0;
            }

            if ($engines) {
                $engineCount = $engines->count();
                $engineTotal = $engineCount * $enginePrice;
            } else {
                $engineTotal = 0;
            }

            $total = $apuTotal + $engineTotal;

            $final = $total / 100;

            // find out if user is premium, if so return this
            return view('newlistings.paymentform')
                ->with('premium', false)
                ->with('apus', $apus)
                ->with('engines', $engines)
                ->with('customer', $customer)
                ->with('apuPrice', $apuPrice)
                ->with('total', $final)
                ->with('error', 'buttsecks');
        } else {
            return redirect()->back();
        }
    }

    public function renewListing(Request $request)
    {

        // SET VARIABLES
        $user = Auth::user(); // Get User
        \Stripe\Stripe::setApiKey(env('STRIPE_SECRET')); // Set API Key
        $customer = \Stripe\Customer::retrieve($user->stripe_id); // Get Customer object

        $listing = $model->id;

        $order =   \Stripe\Order::create([
                "currency" => "usd",
                "email" => $user->email,
                "items" => [
                    "type" => "sku",
                    "parent" => $request->sku,
                    "quantity"=> $request->quantity,
                    "description" => "Listing Renewal"
                ],
            ]);


        $listing->renew();
    }
}

resources/views/newlistings/includes/_apucreateform.blade.php
<legend>Create New Listing - {{ $type }}</legend>
{{--CREATE APU FORM--}}
<form class="apu-form"  enctype="multipart/form-data" method="POST" action="/apus">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">


    {{--Error Display--}}
    @if($errors->any())
        <div class="alert alert-danger" role="alert">
            <i class="fa fa-exclamation-circle" aria-hidden="true"></i><strong> Whoops!</strong> There were some errors with your submission. See details below.
            <hr>
          <?php  foreach ($errors->all() as $message) {
   echo '<p>'.$message.'</p>';
} ?>
        </div>
        @endif
        <div class="row">

            {{--Part Number--}}
            <div class="part-number col-sm-6">
                <div class="form-group @if ($errors->has('part_number')) has-error @endif">
                    <label for="part_number">Part Number</label>
                    <input type="text" class="form-control" name="part_number" value="{{ old('part_number') }}" >
                </div>
            </div>

            {{--Serial Number--}}
            <div class="serial col-sm-6">
                <div class="form-group @if ($errors->has('serial')) has-error @endif">
                    <label for="serial_number">Serial Number</label>
                    <input type="text" class="form-control" name="serial" value="{{ old('serial') }}" >
                </div>
            </div>

            {{--Model Number--}}
            <div class="model col-sm-6">
                <div class="form-group @if ($errors->has('model')) has-error @endif">
                    <label for="model_number ">Model Number</label>
                    <input type="text" class="form-control" name="model" value="{{ old('model') }}">
                </div>
            </div>

            {{--Condition--}}
            <div class="col-sm-6">

                <div class="form-group @if ($errors->has('condition')) has-error @endif">
                <label for="condition">Condition</label>
                <select class="form-control" name="condition" id="condition">

                    @if(!old('condition'))
                    <option value="" selected>Select</option>
                    @else
                        <option value="">Select</option>
                    @endif

                        {{--AS REMOVED--}}
                        @if(old('condition') == 'AR' )
                            <option value="AR" selected>As-Removed</option>
                            @else
                            <option value="AR">As-Removed</option>
                            @endif

                        {{--SV--}}
                        @if(old('condition') == 'SV' )
                            <option value="SV" selected>Serviceable</option>
                        @else
                            <option value="SV">Serviceable</option>
                        @endif

                        {{--OH--}}
                        @if(old('condition') == 'OH' )
                            <option value="OH" selected>Overhauled</option>
                        @else
                            <option value="OH">Overhauled</option>
                        @endif

                        {{--NE--}}
                        @if(old('condition') == 'NE' )
                            <option value="NE" selected>New</option>
                        @else
                            <option value="NE">New</option>
                        @endif
                </select>
                    </div>
            </div>



            {{--8130--}}

            <div class="8130-details well col-sm-12">
                <legend><small>Tag Details</small></legend>
                     <div class="form-group @if ($errors->has('tagged_by')) has-error @endif">

                         <label for="8130_shop_name">Tagged By</label>
                         <input @if(old('condition') == 'SV' or old('condition') == 'OH' or old('condition') == 'NE') value="{{ old('tagged_by') }}" @endif type="text" class="8130 form-control" name="tagged_by"  @if (old('condition') == 'SV' or old('condition') == 'OH' or old('condition') == 'NE') disabled="false" @else disabled="true" @endif>
                     </div>



                <div class="row">
                    <div class="col-sm-8">
                        <div class="form-group @if ($errors->has('details')) has-error @endif">
                        <label>8130 Block Details</label>
                        <textarea name="details" class="8130 8130-details form-control" disabled="true">{{ old('details') }}</textarea>
                            </div>
                    </div>

                        {{--TAG DATE--}}
                    <div class="col-sm-4">
                        <label>Tag Date</label>
                        <div class="form-group">
                            {{--TAG MONTH--}}
                        <div class="col-xs-4">
                            <div class="form-group @if ($errors->has('tag_month')) has-error @endif">

                            <input type="text" class="8130 form-control" name="tag_month"  disabled="true" value="{{ old('tag_month') }}">
                            <span id="helpBlock" class="text-center help-block"><small>Month</small></span>
                                </div>
                        </div>
                            {{--TAG DAY--}}
                        <div class="col-xs-4">
                            <div class="form-group @if ($errors->has('tag_day')) has-error @endif">
                            <input type="text" class="8130 form-control" name="tag_day"  disabled="true" value="{{ old('tag_day') }}">
                            <span id="helpBlock" class="text-center help-block"><small>Day</small></span>
                                </div>
                        </div>

                            {{--TAG YEAR--}}
                        <div class="col-xs-4">
                            <div class="form-group @if ($errors->has('tag_day')) has-error @endif">
                            <input type="text" class="8130 form-control" name="tagged_year"  disabled="true" value="{{ old('tag_year') }}">
                            <span id="helpBlock" class="text-center help-block"><small>Year</small></span>
                        </div>
                            </div>
                            </div>



                    </div>
                </div>




            </div>

        {{--===== TIMES & CYCLES ======--}}
<legend><small>Times & Cycles</small></legend>
            {{--TSN--}}
            <div class="tsn col-sm-3">
                <div class="form-group">
                    <label for="tsn">TSN</label>
                    <input autocomplete="off" type="text" class="form-control" name="tsn" value="{{ old('tsn') }}">
                    <span id="helpBlock" class="help-block"><small>Time Since New</small></span>
                </div>
            </div>

            {{--CSN--}}
            <div class="tsn col-sm-3">
                <div class="form-group">
                    <label for="csn">CSN</label>
                    <input autocomplete="off" type="text" class="form-control" name="csn" value="{{ old('csn') }}" >
                    <span id="helpBlock" class="help-block"><small>Cycles Since New</small></span>
                </div>
            </div>

            {{--TSLSV--}}
            <div class="tsn col-sm-3">
                <div class="form-group">
                    <label for="tslsv">TSLSV</label>
                    <input  autocomplete="off" type="text" class="form-control" name="tslsv" value="{{ old('tslsv') }}">
                    <span id="helpBlock" class="help-block"><small>Time Since Last Shop Visit</small></span>
                </div>

            </div>

            {{--CSLSV--}}
            <div class="tsn col-sm-3">
                <div class="form-group">
                    <label for="cslsv">CSLSV</label>
                    <input autocomplete="off" type="text" class="form-control" name="cslsv"value="{{ old('cslsv') }}" >
                    <span id="helpBlock" class="help-block"><small>Cycles Since Last Shop Visit</small></span>
                </div>



            </div>


            <legend><small>Trace & Terms</small></legend>

                {{--Trace--}}
                <div class="part-number col-sm-3">
                    <div class="form-group">
                        <label for="trace">Trace</label>
                        <select class="form-control" name="trace" id="trace">


                            @if(!old('condition'))
                                <option selected>Select</option>
                            @else
                                <option>Select</option>
                            @endif

                            {{--121--}}
                            @if(old('trace') == '121' )
                                <option value="121" selected>121 Operator</option>
                            @else
                                <option value="121">121 Operator</option>
                            @endif

                            {{--129--}}
                            @if(old('trace') == '129' )
                                <option value="129" selected>129 Operator</option>
                            @else
                                <option value="129">129 Operator</option>
                            @endif

                            {{--135--}}
                            @if(old('trace') == '135' )
                                <option value="135" selected>135 Operator</option>
                            @else
                                <option value="135">135 Operator</option>
                            @endif

                            {{--145--}}
                            @if(old('trace') == '145' )
                                <option value="145" selected>145 Repair Station</option>
                            @else
                                <option value="145">145 Repair Station</option>
                            @endif

                            {{--Foreign--}}
                            @if(old('trace') == 'Foreign' )
                                <option value="Foreign" selected>Foreign Operator</option>
                            @else
                                <option value="Foreign">Foreign Operator</option>
                            @endif

                            {{--NA--}}
                            @if(old('trace') == 'NA' )
                                <option value="NA" selected>NA</option>
                            @else
                                <option value="NA">NA</option>
                            @endif

                        </select>
                    </div>
                </div>

            <div class="col-sm-3">

                <label for="tslsv">Minipack URL</label>

                <input autocomplete="off" type="text" class="form-control" name="minipack" value="{{ old('minipack') }}">
                <span class="help-block"><small><i class="fa fa-dropbox" aria-hidden="true"></i> DropBox URL (or other)</small></span>



            </div>

                {{--Terms--}}
                <div class="serial col-sm-5">
                    <div class="form-group">
                        <label>Terms</label>
                        <p></p>
                        <label class="checkbox-inline">

                            <input type="checkbox" name="outright" value="outright" @if(old('outright')) checked @endif > Outright Sale
                        </label>
                        <label class="checkbox-inline">
                            <input type="checkbox" name="exchange" value="exchange" @if(old('exchange')) checked @endif > Exchange
                        </label>
                        <label class="checkbox-inline">
                            <input type="checkbox" name="lease" value="lease" @if(old('lease')) checked @endif > Lease
                        </label>
                    </div>

            </div>




        </div>


        <div class="row">
            <div class="sale-terms col-sm-12">
                <div class="form-group">
                    <textarea class="form-control" readonly="readonly">{!! config('app.TOS') !!}</textarea>
                    <label class="checkbox-inline">
                        <input type="checkbox" id="agreement" name="agreement"> I agree to Teardown Aero LLC Terms of Service.
                    </label>

                </div>

            </div>

        </div>





    <button class="btn btn-primary" id="new-apu-submit"  type="submit">Done</button>


</form>

resources/views/newlistings/includes/_newlistingseditsidebar.blade.php
<p class="text-center"><strong>Listings Cart</strong></p>
<p></p>


        {{--If user has Engines to list--}}


        @if(!$engines->isEmpty())
            <legend><small>Engines</small></legend>
            <ul class="list-unstyled">
                @foreach($engines as $engine)

                    <li style="margin-bottom:20px;">
                        <div class="row">
                            <div class="col-xs-8">{{ $engine->model }}{{ $engine->minor_variant }} <p><small>SN <strong> {{ $engine->serial }}</strong> - PN <strong>{{ $engine->part_number }}</strong></small></p>
                                <p style="margin-top:-10px;"><small>
                                        {{ Form::open(array('route' => array('engines.destroy', $engine->id), 'method' => 'delete')) }}
                                        <button class="btn btn-xs btn-default"  type="submit">Delete Listing</button>
                                        {{ Form::close() }}



                                    </small></p>

                            </div>
                            <div class="col-xs-4"><a href="{{ route('engines.edit',$engine->id) }}" class="pull-right btn btn-xs btn-default">Edit</a></div></div></li>


                @endforeach
            </ul>
        @endif
<p></p>


        {{--If user has APUs to list--}}
        @if(!$apus->isEmpty())
            <legend><small>APUS</small></legend>
            <ul class="list-unstyled">
                @foreach($apus as $apu)

                    <li style="margin-bottom:20px;">
                        <div class="row">




                            <div class="col-xs-8">{{ $apu->model }} <p><small>SN <strong> {{ $apu->serial }}</strong> - PN <strong>{{ $apu->part_number }}</strong></small></p>
                            <p style="margin-top:-10px;"><small>
                                    {{ Form::open(array('route' => array('apus.destroy', $apu->id), 'method' => 'delete')) }}
                                    <button class="btn btn-xs btn-default"  type="submit">Delete Listing</button>
                                    {{ Form::close() }}



                                </small></p></div>
                            <div class="col-xs-4"><a href="{{ route('apus.edit',$apu->id) }}" class="pull-right btn btn-xs btn-default">Edit</a>
                                </div></div></li>


                @endforeach
            </ul>
        @endif





    <div class="row"></div>
    <div class="col-xs-12">
        @if($user->hasUnpublished())

           {{--make this a dropdown button--}}
            <div class="dropdown">
                <button class="btn navbar-btn btn-default btn-block dropdown-toggle" type="button" id="add_another_sidebar" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    <i class="fa fa-plus" aria-hidden="true"></i> Add Another
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" aria-labelledby="add_another_sidebar">

                    <li><a href="{{ route('engines.create') }}">Engine</a></li>
                    <li><a href="{{ route('apus.create') }}">Auxiliary Power Unit</a></li>
                    <li><a href="#">Aircraft Teardown</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">Market Post</a></li>
                </ul>
            </div>
            @else
            <p class="text-center">No listings saved yet.</p>
            @endif

        @if($user->hasUnpublished())  <a class="btn  btn-primary btn-block" href="{{ route('paymentform') }}">Checkout & Publish</a>@endif


    </div>

resources/views/newlistings/includes/_paymentconfirmationsidebar.blade.php
<div class="well">
    <legend>Confirmation</legend>
</div>